version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4468:4468"
    environment:
      PRISMA_CONFIG: |
        port: 4468
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-209-187-54.compute-1.amazonaws.com
            port: '5432'
            database: dcjp94sp7koihf
            ssl: true
            user: xjpspravcikiij
            password: 3e7bb97c5ad9e7947645d9451026b5847ea7517d81f25211e07f309a55e2ab46
            migrations: true